### ISSUE TITLE
ubuntu 2022.04 编译host image编译报错

### ISSUE THREAD

**Issue by nyl1001** [yunionio/qemu#5]
报错信息如下：make image host-image VERSION=v3.10.8
mkdir -p /root/cloudpods/_output

Start to build component: host-image
make[1]: Entering directory '/root/cloudpods'
go build -mod vendor -ldflags "-w -X yunion.io/x/pkg/util/version.gitVersion=master-20230911.0-497-g4cb021916520a5 -X yunion.io/x/pkg/util/version.gitCommit=4cb0219165 -X yunion.io/x/pkg/util/version.gitBranch=master -X yunion.io/x/pkg/util/version.buildDate=2023-12-18T02:09:41Z -X yunion.io/x/pkg/util/version.gitTreeState=dirty -X yunion.io/x/pkg/util/version.gitMajor=0 -X yunion.io/x/pkg/util/version.gitMinor=0" -o /root/cloudpods/_output/bin/host-image yunion.io/x/onecloud/cmd/host-image
# runtime/cgo
/usr/bin/ld: cannot find -lqemuio: No such file or directory
/usr/bin/ld: cannot find -lgnutls: No such file or directory
/usr/bin/ld: cannot find -lqemuio: No such file or directory
/usr/bin/ld: cannot find -lgnutls: No such file or directory

本人参照https://github.com/yunionio/qemu 编译了qemu，LIBQEMUIO_PATH也指向了qemu根目录，但是编译依然报上述错误，尝试安装了各种依赖包，依然不能解决问题。

**Comment by zexi** [comment]
和这个是相同问题，https://github.com/yunionio/cloudpods/issues/19024
